services:
  db:
    restart: always
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:latest
    volumes:
      - redis_data:/data

  web:
    restart: always
    build: .
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  celery:
    build: .
    command: celery -A reslab_manager worker --loglevel=info
    volumes:
      - .:/src
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A reslabmanager beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/src
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data: